project:
  title: "Trade lunch"
  output-dir: _output

format:
  html:
    theme: lux
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    embed-resources: true

linkcolor: blue